### PR TITLE
adds_favicon

### PR DESCRIPTION
**Pull request by jemiw**
Added favicon png and included link tag in index.html

### CODE REVIEW

**Comment by markreid** [comment]
@fruuf will have to explain how to get it from `src` to `dist` during the build process.

**Comment by jemiw** [comment]
I can probably figure it out ok. I'll ask if I can't though

**Comment by markreid** [comment]
i couldn't :grimacing:

**Comment by jemiw** [comment]
ahh. ok i'll ask then!

**Pull request merged**
